---
plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - gemfiles/*
    - lib/store_base_sti_class_for_*.rb

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 150

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false

#########
# RSPEC #
#########

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: to_not
